/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetterScrollBar: typeof import('./../src/components/custom/BetterScrollBar.vue')['default']
    ExceptionBase: typeof import('./../src/components/common/ExceptionBase.vue')['default']
    IconLocalNoPermission: typeof import('~icons/local/no-permission')['default']
    IconLocalNotFound: typeof import('~icons/local/not-found')['default']
    IconLocalServiceError: typeof import('~icons/local/service-error')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    'IconPh:caretCircleDownFill': typeof import('~icons/ph/caret-circle-down-fill')['default']
    'IconPh:caretCircleUpFill': typeof import('~icons/ph/caret-circle-up-fill')['default']
    LayoutSliderMenu: typeof import('./../src/components/common/LayoutSliderMenu.vue')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEl: typeof import('naive-ui')['NEl']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RadioButtonGroup: typeof import('./../src/components/custom/RadioButtonGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderMenu: typeof import('./../src/components/common/SliderMenu.vue')['default']
    SvgIcon: typeof import('./../src/components/custom/SvgIcon.vue')['default']
    VirtualListGrid: typeof import('./../src/components/custom/VirtualListGrid.vue')['default']
  }
}
