/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomScroll: typeof import('./../src/components/common/CustomScroll.vue')['default']
    CustomScrollBar: typeof import('./../src/components/common/CustomScrollBar.vue')['default']
    ExceptionBase: typeof import('./../src/components/common/ExceptionBase.vue')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    'IconPh:caretCircleDownFill': typeof import('~icons/ph/caret-circle-down-fill')['default']
    'IconPh:caretCircleUpFill': typeof import('~icons/ph/caret-circle-up-fill')['default']
    'IconPh:checkCircleFill': typeof import('~icons/ph/check-circle-fill')['default']
    NaiveProvider: typeof import('./../src/components/common/NaiveProvider.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    RadioButton: typeof import('./../src/components/common/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderMenu: typeof import('./../src/components/common/SliderMenu.vue')['default']
  }
}
